// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'widget_registry.freezed.dart';

enum ClientStatus {
  connected,
  disconnected,
  ;
}

class Coord {
  final double x;
  final double y;

  const Coord({
    required this.x,
    required this.y,
  });

  @override
  int get hashCode => x.hashCode ^ y.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Coord &&
          runtimeType == other.runtimeType &&
          x == other.x &&
          y == other.y;
}

@freezed
sealed class ResultRegistry with _$ResultRegistry {
  const ResultRegistry._();

  const factory ResultRegistry.confirmResult({
    required bool status,
  }) = ResultRegistry_ConfirmResult;
  const factory ResultRegistry.errorResult({
    required String error,
  }) = ResultRegistry_ErrorResult;
}

enum ServerStatus {
  notInit,
  idle,
  busy,
  error,
  ;
}

@freezed
sealed class WidgetRegistry with _$WidgetRegistry {
  const WidgetRegistry._();

  const factory WidgetRegistry.clickButton() = WidgetRegistry_ClickButton;
  const factory WidgetRegistry.toggleButton({
    required bool value,
  }) = WidgetRegistry_ToggleButton;
  const factory WidgetRegistry.confirmButton() = WidgetRegistry_ConfirmButton;
  const factory WidgetRegistry.pressButton({
    required bool pressed,
  }) = WidgetRegistry_PressButton;
  const factory WidgetRegistry.directionalButton({
    required int direction,
  }) = WidgetRegistry_DirectionalButton;
  const factory WidgetRegistry.joystick({
    required Coord delta,
    required double intensity,
  }) = WidgetRegistry_Joystick;
}
