// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.24.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'server/com_socket.dart';
part 'server.freezed.dart';

@freezed
sealed class ServerProtocol with _$ServerProtocol {
  const factory ServerProtocol.socket(
    T field0,
  ) = ServerProtocol_Socket;
}
