// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.24.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import '../../models/widget_registry.dart';
import 'codde_pi_client.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class ComSocketClient {
  final String address;
  final TcpStream? stream;

  const ComSocketClient({
    required this.address,
    this.stream,
  });

  static Future<ComSocketClient> newComSocketClient(
          {required Str address, dynamic hint}) =>
      RustLib.instance.api.comSocketClientNew(address: address, hint: hint);

  @override
  int get hashCode => address.hashCode ^ stream.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ComSocketClient &&
          runtimeType == other.runtimeType &&
          address == other.address &&
          stream == other.stream;
}
