// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.30.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'base/protocol.dart';
import 'com_socket.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class CoddePiClient {
  const CoddePiClient();

  static Future<void> dummy(
          {required Protocol protocol, required String addr, dynamic hint}) =>
      RustLib.instance.api.coddePiClientDummy(
        protocol: protocol,
        addr: addr,
        hint: hint,
      );

  static Future<ComSocketClient> useSocket(
          {required String address, dynamic hint}) =>
      RustLib.instance.api.coddePiClientUseSocket(
        address: address,
        hint: hint,
      );

  @override
  int get hashCode => 0;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CoddePiClient && runtimeType == other.runtimeType;
}
