// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'base/protocol.dart';
import 'com_socket.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class CoddePiClient {
  const CoddePiClient();

  static Future<void> dummy(
          {required Protocol protocol, required String addr}) =>
      RustLib.instance.api.crateApiCoddePiClientCoddePiClientDummy(
          protocol: protocol, addr: addr);

  static Future<ComSocketClient> useSocket({required String address}) =>
      RustLib.instance.api
          .crateApiCoddePiClientCoddePiClientUseSocket(address: address);

  @override
  int get hashCode => 0;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CoddePiClient && runtimeType == other.runtimeType;
}
