// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'base/error.dart';
import 'base/frame.dart';
import 'base/widget_registry.dart';
import 'com.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ComSocketClient>>
abstract class ComSocketClient implements RustOpaqueInterface, ClientCom {
  String get address;

  ClientStatus get status;

  set address(String address);

  set status(ClientStatus status);

  @override
  Future<void> connect();

  @override
  Future<void> disconnect();

  @override
  Future<bool> isConnected();

  factory ComSocketClient({required String address}) => RustLib.instance.api
      .crateApiComSocketComSocketClientNew(address: address);

  @override
  Future<ResultFrame?> receive();

  /// Expose method twice for Dart port
  /// Rust Flutter Bridge only read direct struct implementations
  @override
  Future<ResultFrame?> request({required Frame data});

  @override
  Future<void> send({required Frame data});
}
