// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/base/error.dart';
import 'api/base/frame.dart';
import 'api/base/protocol.dart';
import 'api/base/widget_registry.dart';
import 'api/codde_pi_client.dart';
import 'api/com.dart';
import 'api/com_socket.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_ComSocketClientPtr => wire
          ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerComSocketClientPtr;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  ComSocketClient
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerComSocketClient(
          dynamic raw);

  @protected
  ComSocketClient
      dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerComSocketClient(
          dynamic raw);

  @protected
  ComSocketClient
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerComSocketClient(
          dynamic raw);

  @protected
  ComSocketClient
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerComSocketClient(
          dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  ClientCom dco_decode_TraitDef_ClientCom(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  Coord dco_decode_box_autoadd_coord(dynamic raw);

  @protected
  Frame dco_decode_box_autoadd_frame(dynamic raw);

  @protected
  ResultFrame dco_decode_box_autoadd_result_frame(dynamic raw);

  @protected
  WidgetRegistry dco_decode_box_autoadd_widget_registry(dynamic raw);

  @protected
  ClientStatus dco_decode_client_status(dynamic raw);

  @protected
  CoddePiClient dco_decode_codde_pi_client(dynamic raw);

  @protected
  Coord dco_decode_coord(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  Frame dco_decode_frame(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  Frame? dco_decode_opt_box_autoadd_frame(dynamic raw);

  @protected
  ResultFrame? dco_decode_opt_box_autoadd_result_frame(dynamic raw);

  @protected
  Protocol dco_decode_protocol(dynamic raw);

  @protected
  (int, String) dco_decode_record_u_8_string(dynamic raw);

  @protected
  ResultFrame dco_decode_result_frame(dynamic raw);

  @protected
  ResultRegistry dco_decode_result_registry(dynamic raw);

  @protected
  ServerStateError dco_decode_server_state_error(dynamic raw);

  @protected
  ServerStatus dco_decode_server_status(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  WidgetRegistry dco_decode_widget_registry(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  ComSocketClient
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerComSocketClient(
          SseDeserializer deserializer);

  @protected
  ComSocketClient
      sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerComSocketClient(
          SseDeserializer deserializer);

  @protected
  ComSocketClient
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerComSocketClient(
          SseDeserializer deserializer);

  @protected
  ComSocketClient
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerComSocketClient(
          SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  Coord sse_decode_box_autoadd_coord(SseDeserializer deserializer);

  @protected
  Frame sse_decode_box_autoadd_frame(SseDeserializer deserializer);

  @protected
  ResultFrame sse_decode_box_autoadd_result_frame(SseDeserializer deserializer);

  @protected
  WidgetRegistry sse_decode_box_autoadd_widget_registry(
      SseDeserializer deserializer);

  @protected
  ClientStatus sse_decode_client_status(SseDeserializer deserializer);

  @protected
  CoddePiClient sse_decode_codde_pi_client(SseDeserializer deserializer);

  @protected
  Coord sse_decode_coord(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  Frame sse_decode_frame(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  Frame? sse_decode_opt_box_autoadd_frame(SseDeserializer deserializer);

  @protected
  ResultFrame? sse_decode_opt_box_autoadd_result_frame(
      SseDeserializer deserializer);

  @protected
  Protocol sse_decode_protocol(SseDeserializer deserializer);

  @protected
  (int, String) sse_decode_record_u_8_string(SseDeserializer deserializer);

  @protected
  ResultFrame sse_decode_result_frame(SseDeserializer deserializer);

  @protected
  ResultRegistry sse_decode_result_registry(SseDeserializer deserializer);

  @protected
  ServerStateError sse_decode_server_state_error(SseDeserializer deserializer);

  @protected
  ServerStatus sse_decode_server_status(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  WidgetRegistry sse_decode_widget_registry(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerComSocketClient(
          ComSocketClient self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerComSocketClient(
          ComSocketClient self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerComSocketClient(
          ComSocketClient self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerComSocketClient(
          ComSocketClient self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_coord(Coord self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_frame(Frame self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_result_frame(
      ResultFrame self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_widget_registry(
      WidgetRegistry self, SseSerializer serializer);

  @protected
  void sse_encode_client_status(ClientStatus self, SseSerializer serializer);

  @protected
  void sse_encode_codde_pi_client(CoddePiClient self, SseSerializer serializer);

  @protected
  void sse_encode_coord(Coord self, SseSerializer serializer);

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_frame(Frame self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_frame(Frame? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_result_frame(
      ResultFrame? self, SseSerializer serializer);

  @protected
  void sse_encode_protocol(Protocol self, SseSerializer serializer);

  @protected
  void sse_encode_record_u_8_string(
      (int, String) self, SseSerializer serializer);

  @protected
  void sse_encode_result_frame(ResultFrame self, SseSerializer serializer);

  @protected
  void sse_encode_result_registry(
      ResultRegistry self, SseSerializer serializer);

  @protected
  void sse_encode_server_state_error(
      ServerStateError self, SseSerializer serializer);

  @protected
  void sse_encode_server_status(ServerStatus self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_widget_registry(
      WidgetRegistry self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerComSocketClient(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerComSocketClient(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerComSocketClientPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_codde_protocol_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerComSocketClient');
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerComSocketClient =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerComSocketClientPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerComSocketClient(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerComSocketClient(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerComSocketClientPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_codde_protocol_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerComSocketClient');
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerComSocketClient =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerComSocketClientPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();
}
